const products = [
  {
    id: 1,
    image1: "./src/assets/imgs/img1.jpg",
    image2: "./src/assets/imgs/img1_1.jpg",
    title: "Bộ keycap cherry doraemon",
    price: 525000,
    salePercent: 24,
    brand: "Stooges",
    type: "Keycap bộ",
  },
  {
    id: 2,
    image1: "./src/assets/imgs/img2.jpg",
    image2: "./src/assets/imgs/img2_1.jpg",
    title: "Túi đựng bàn phím, chống sốc, chống xước",
    price: 80000,
    salePercent: 14,
    brand: "Kelowna",
    type: "Phụ kiện bàn phím",
  },
  {
    id: 3,
    image1: "./src/assets/imgs/img3.png",
    image2: "./src/assets/imgs/img3_1.jpg",
    title: "Bộ keycap silent forest",
    price: 780000,
    salePercent: null,
    brand: "Cmk",
    type: "Keycap bộ",
  },
  {
    id: 4,
    image1: "./src/assets/imgs/img4.jpg",
    image2: "./src/assets/imgs/img4_1.jpg",
    title: "Bàn phím cơ cmk75 | fl-esports",
    price: 2550000,
    salePercent: 14,
    brand: "Fl - esports",
    type: "Bàn phím cơ",
  },
  {
    id: 5,
    image1: "./src/assets/imgs/img5.jpg",
    image2: "./src/assets/imgs/img5_1.jpg",
    title: "Bộ keycap chocolate donut",
    price: 699000,
    salePercent: null,
    brand: "Cmk",
    type: "Keycap bộ",
  },
  {
    id: 6,
    image1: "./src/assets/imgs/img6.png",
    image2: "./src/assets/imgs/img6_1.jpg",
    title: "Switch ws morandi",
    price: 10500,
    salePercent: 14,
    brand: "Wuque studio",
    type: "Switch",
  },
  {
    id: 7,
    image1: "./src/assets/imgs/img7.jpg",
    image2: "./src/assets/imgs/img7_1.jpg",
    title: "Bàn phím cơ custom infiverse infi75",
    price: 2500000,
    salePercent: null,
    brand: "Infiverse",
    type: "Bàn phím cơ",
  },
  {
    id: 8,
    image1: "./src/assets/imgs/img8.jpg",
    image2: "./src/assets/imgs/img8_1.jpg",
    title: "Plate nhôm cho bàn phím cơ",
    price: 270000,
    salePercent: null,
    brand: "Kicap",
    type: "Phụ kiện",
  },
  {
    id: 9,
    image1: "./src/assets/imgs/img9.jpg",
    image2: "./src/assets/imgs/img9_1.jpg",
    title: "Bộ keycap sa colourful dream",
    price: 1100000,
    salePercent: null,
    brand: "Osiris",
    type: "Keycap bộ",
  },
  {
    id: 10,
    image1: "./src/assets/imgs/img10.png",
    image2: "./src/assets/imgs/img10_1.jpg",
    title: "Bàn phím cơ kit finalkey v81 plus",
    price: 1100000,
    salePercent: 9,
    brand: "Finalkey",
    type: "Kit",
  },
  {
    id: 11,
    image1: "./src/assets/imgs/img11.png",
    image2: "./src/assets/imgs/img11_1.png",
    title: "Bộ keycap p5 persona5",
    price: 900000,
    salePercent: 11,
    brand: "Xt-design",
    type: "Keycap bộ",
  },
  {
    id: 12,
    image1: "./src/assets/imgs/img12.jpg",
    image2: "./src/assets/imgs/img12_1.jpg",
    title: "Bộ keycap p5 persona5",
    price: 525000,
    salePercent: 18,
    brand: "Xt-design",
    type: "Keycap bộ",
  },
];

export default products;
