const products = [
  {
    id: 1,
    image1: "./src/assets/imgs/img1.jpg",
    image2: "./src/assets/imgs/img1_1.jpg",
    title: "Bộ keycap xda commando",
    price: 499000,
    salePercent: 14,
    brand: "CMK",
    type: "keycap bộ",
  },
  {
    id: 2,
    image1: "./src/assets/imgs/img2.jpg",
    image2: "./src/assets/imgs/img2_1.jpg",
    title: "BỘ KEYCAP SA DANDELION",
    price: 1200000,
    salePercent: null,
    brand: "OSIRIS",
    type: "keycap bộ",
  },
  {
    id: 3,
    image1: "./src/assets/imgs/img3.png",
    image2: "./src/assets/imgs/img3_1.jpg",
    title: "SWITCH WUQUE STUDIO",
    price: 9400,
    salePercent: null,
    brand: "WUQUE STUDIO",
    type: "switch",
  },
  {
    id: 4,
    image1: "./src/assets/imgs/img4.jpg",
    image2: "./src/assets/imgs/img4_1.jpg",
    title: "BỘ KEYCAP PS DESIGN",
    price: 800000,
    salePercent: 6,
    brand: "TUT",
    type: "keycap bộ",
  },
  {
    id: 5,
    image1: "./src/assets/imgs/img5.jpg",
    image2: "./src/assets/imgs/img5_1.jpg",
    title: "SWITCH JELLY STRAWBERRY V2",
    price: 7500,
    salePercent: 20,
    brand: null,
    type: "switch",
  },
  {
    id: 6,
    image1: "./src/assets/imgs/img6.png",
    image2: "./src/assets/imgs/img6_1.jpg",
    title: "BÀN PHÍM CƠ TÙY CHỈNH KIT GMK67 - ZOUYA",
    price: 1050000,
    salePercent: 19,
    brand: "ZOUYA",
    type: "kit",
  },
  {
    id: 7,
    image1: "./src/assets/imgs/img7.jpg",
    image2: "./src/assets/imgs/img7_1.jpg",
    title: "BỘ KEYCAP CMK BOW/WOB/RED",
    price: 400000,
    salePercent: 12,
    brand: "AIFEI",
    type: "keycap bộ",
  },
  {
    id: 8,
    image1: "./src/assets/imgs/img8.jpg",
    image2: "./src/assets/imgs/img8_1.jpg",
    title: "BỘ KEYCAP NAHIDA GRASS GOD",
    price: 890000,
    salePercent: 14,
    brand: "XT-DESIGN",
    type: "keycap bộ",
  },
  {
    id: 9,
    image1: "./src/assets/imgs/img9.png",
    image2: "./src/assets/imgs/img9_1.png",
    title: "BÀN PHÍM CƠ TÙY CHỈNH KIT V65 R2",
    price: 2400000,
    salePercent: null,
    brand: "CIDOO",
    type: "kit",
  },
  {
    id: 10,
    image1: "./src/assets/imgs/img10.png",
    image2: "./src/assets/imgs/img10_1.png",
    title: "BỘ KEYCAP CMK MODERN DOLCH LIGHT - RETRO",
    price: 400000,
    salePercent: null,
    brand: "AIFEI",
    type: "keycap bộ",
  },
  {
    id: 11,
    image1: "./src/assets/imgs/img11.png",
    image2: "./src/assets/imgs/img11_1.jpg",
    title: "SWITCH AKKO CREAM YELLOW/BLUE V3",
    price: 7000,
    salePercent: 26,
    brand: "AKKO",
    type: "switch",
  },
  {
    id: 12,
    image1: "./src/assets/imgs/img12.png",
    image2: "./src/assets/imgs/img12_1.png",
    title: "BÀN PHÍM CƠ GP75 FL-ESPORTS",
    price: 2350000,
    salePercent: null,
    brand: "FL - ESPORTS",
    type: "bàn phím cơ",
  },
  {
    id: 13,
    image1: "./src/assets/imgs/img13.jpg",
    image2: "./src/assets/imgs/img13_1.jpg",
    title: "BỘ KEYCAP CMK MODERN DOLCH",
    price: 450000,
    salePercent: 16,
    brand: "AIFEI",
    type: "keycap bộ",
  },
  {
    id: 14,
    image1: "./src/assets/imgs/img14.jpg",
    image2: "./src/assets/imgs/img14_1.jpg",
    title: "BỘ KEYCAP XDA EMILIA",
    price: 500000,
    salePercent: 20,
    brand: "SOY SAUCE",
    type: "keycap bộ",
  },
  {
    id: 15,
    image1: "./src/assets/imgs/img15.jpg",
    image2: "./src/assets/imgs/img15_1.jpg",
    title: "BỘ KEYCAP CHERRY RICE SHOWER",
    price: 830000,
    salePercent: 10,
    brand: "XT-DESIGN",
    type: "keycap bộ",
  },
  {
    id: 16,
    image1: "./src/assets/imgs/img16.jpg",
    image2: "./src/assets/imgs/img16_1.jpg",
    title: "SWITCH KTT MATCHA - TACTILE",
    price: 10000,
    salePercent: 10,
    brand: "KTT",
    type: "switch",
  },
  {
    id: 17,
    image1: "./src/assets/imgs/img17.png",
    image2: "./src/assets/imgs/img17_1.png",
    title: "BÀN PHÍM CƠ CUSTOM MONSGEEK M3 NHÔM CNC",
    price: 1800000,
    salePercent: null,
    brand: "MONSGEEK",
    type: "bàn phím cơ",
  },
  {
    id: 18,
    image1: "./src/assets/imgs/img18.jpg",
    image2: "./src/assets/imgs/img18_1.jpg",
    title: "BỘ KEYCAP BOCCHI THE ROCK",
    price: 850000,
    salePercent: 8,
    brand: "XT-DESIGN",
    type: "keycap bộ",
  },
  {
    id: 19,
    image1: "./src/assets/imgs/img19.jpg",
    image2: "./src/assets/imgs/img19_1.png",
    title: "BÀN PHÍM CƠ KIT LMK81 - ZUOYA",
    price: 2300000,
    salePercent: null,
    brand: "ZUOYA",
    type: "bàn phím cơ",
  },
  {
    id: 20,
    image1: "./src/assets/imgs/img20.jpg",
    image2: "./src/assets/imgs/img20_1.jpg",
    title: "SWITCH GATERON PURE BERRY X MODERN GREY LINEAR SWITCH",
    price: 525000,
    salePercent: 14,
    brand: "GATERON",
    type: "switch",
  },
  {
    id: 21,
    image1: "./src/assets/imgs/img21.jpg",
    image2: "./src/assets/imgs/img21_1.jpg",
    title: "BỘ KEYCAP NEWTOY X WUKDS 1970",
    price: 1200000,
    salePercent: 12,
    brand: "WUKDS",
    type: "keycap bộ",
  },
  {
    id: 22,
    image1: "./src/assets/imgs/img22.jpg",
    image2: "./src/assets/imgs/img22_1.jpg",
    title: "BỘ KEYCAP RETRO 1980",
    price: 800000,
    salePercent: 6,
    brand: "M7",
    type: "keycap bộ",
  },
  {
    id: 23,
    image1: "./src/assets/imgs/img23.jpg",
    image2: "./src/assets/imgs/img23_1.jpg",
    title: "BỘ KEYCAP CMK RESONANCE",
    price: 650000,
    salePercent: 8,
    brand: "CMK",
    type: "keycap bộ",
  },
  {
    id: 24,
    image1: "./src/assets/imgs/img24.jpg",
    image2: "./src/assets/imgs/img24_1.jpg",
    title: "BỘ KEYCAP CMK RESONANCE",
    price: 520000,
    salePercent: 4,
    brand: "STOOGES",
    type: "keycap bộ",
  },
  {
    id: 25,
    image1: "./src/assets/imgs/img25.jpg",
    image2: "./src/assets/imgs/img25_1.jpg",
    title: "BỘ KEYCAP QUANTUM COMPUTER",
    price: 800000,
    salePercent: 13,
    brand: "MG",
    type: "keycap bộ",
  },
  {
    id: 26,
    image1: "./src/assets/imgs/img26.jpg",
    image2: "./src/assets/imgs/img26_1.jpg",
    title: "BỘ KEYCAP THẢO THẦN NAHIDA",
    price: 600000,
    salePercent: 8,
    brand: "CMK",
    type: "keycap bộ",
  },
  {
    id: 27,
    image1: "./src/assets/imgs/img27.jpg",
    image2: "./src/assets/imgs/img27_1.jpg",
    title: "BỘ KEYCAP SA EGYPT [PRE-ORDER]",
    price: 1290000,
    salePercent: 7,
    brand: "OSIRIS",
    type: "keycap bộ",
  },
  {
    id: 28,
    image1: "./src/assets/imgs/img28.jpg",
    image2: "./src/assets/imgs/img28_1.jpg",
    title: "BỘ KEYCAP MG RAINBOW",
    price: 850000,
    salePercent: 24,
    brand: "MG",
    type: "keycap bộ",
  },
  {
    id: 29,
    image1: "./src/assets/imgs/img29.jpg",
    image2: "./src/assets/imgs/img29_1.jpg",
    title: "BỘ KEYCAP VIRTUAL WAR ORIGIN",
    price: 550000,
    salePercent: 18,
    brand: "CMK",
    type: "keycap bộ",
  },
  {
    id: 30,
    image1: "./src/assets/imgs/img30.png",
    image2: "./src/assets/imgs/img30_1.png",
    title: "BỘ KEYCAP P5 PERSONA5",
    price: 900000,
    salePercent: 11,
    brand: "XT-DESIGN",
    type: "keycap bộ",
  },
  {
    id: 31,
    image1: "./src/assets/imgs/img31.png",
    image2: "./src/assets/imgs/img31_1.jpg",
    title: "[HÀNG SẮP VỀ] BÀN PHÍM CƠ KIT FINALKEY V81 PLUS",
    price: 2700000,
    salePercent: 7,
    brand: "FINALKEY",
    type: "kit",
  },
  {
    id: 32,
    image1: "./src/assets/imgs/img32.jpg",
    image2: "./src/assets/imgs/img32_1.jpg",
    title: "BỘ KEYCAP SA COLOURFUL DREAM",
    price: 1100000,
    salePercent: null,
    brand: "OSIRIS",
    type: "keycap bộ",
  },
  {
    id: 33,
    image1: "./src/assets/imgs/img33.png",
    image2: "./src/assets/imgs/img33_1.png",
    title: "PLATE NHÔM CHO BÀN PHÍM CƠ",
    price: 270000,
    salePercent: null,
    brand: "KICAP",
    type: "phụ kiện",
  },
  {
    id: 34,
    image1: "./src/assets/imgs/img34.png",
    image2: "./src/assets/imgs/img34_1.png",
    title: "BÀN PHÍM CƠ CUSTOM INFIVERSE INFI75",
    price: 2500000,
    salePercent: null,
    brand: "INFIVERSE",
    type: "bàn phím cơ",
  },
  {
    id: 35,
    image1: "./src/assets/imgs/img35.png",
    image2: "./src/assets/imgs/img35_1.png",
    title: "SWITCH WS MORANDI",
    price: 10500,
    salePercent: 10,
    brand: "WUQUE STUDIO",
    type: "switch",
  },
  {
    id: 36,
    image1: "./src/assets/imgs/img36.png",
    image2: "./src/assets/imgs/img36_1.png",
    title: "BỘ KEYCAP CHOCOLATE DONUT",
    price: 699000,
    salePercent: null,
    brand: "CMK",
    type: "keycap bộ",
  },
  {
    id: 37,
    image1: "./src/assets/imgs/img37.png",
    image2: "./src/assets/imgs/img37_1.png",
    title: "BÀN PHÍM CƠ CMK75 | FL-ESPORTS",
    price: 2550000,
    salePercent: 14,
    brand: "FL - ESPORTS",
    type: "bàn phím cơ",
  },
  {
    id: 38,
    image1: "./src/assets/imgs/img38.png",
    image2: "./src/assets/imgs/img38_1.png",
    title: "BỘ KEYCAP SILENT FOREST",
    price: 780000,
    salePercent: null,
    brand: "CMK",
    type: "keycap bộ",
  },
  {
    id: 39,
    image1: "./src/assets/imgs/img39.jpg",
    image2: "./src/assets/imgs/img39_1.jpg",
    title: "TÚI ĐỰNG BÀN PHÍM, CHỐNG SỐC, CHỐNG XƯỚC",
    price: 80000,
    salePercent: 14,
    brand: "KELOWNA",
    type: "phụ kiện bàn phím",
  },
  {
    id: 40,
    image1: "./src/assets/imgs/img40.png",
    image2: "./src/assets/imgs/img40_1.png",
    title: "BỘ KEYCAP CHERRY DORAEMON",
    price: 525000,
    salePercent: 5,
    brand: "STOOGES",
    type: "keycap bộ",
  },
];

export default products;
